### ISSUE TITLE
Explicit version in composer.json

### ISSUE THREAD

**Issue by Maikuolan** [Skocimis/textflow-php#2]
https://github.com/Skocimis/textflow-php/blob/6519b6b9befb5f4d0f1192b4f722fc10cb360562/composer.json#L4

*See: https://packagist.org/about#managing-package-versions*

> ### Managing package versions
> New versions of your package are automatically fetched from tags you create in your VCS repository.
> 
> The easiest way to manage versioning is to just omit the version field from the composer.json file. The version numbers will then be parsed from the tag and branch names.

Would be better to remove that line and just create new [tags](https://github.com/Skocimis/textflow-php/tags) for new versions here instead. Let Packagist figure out which versions of your code are available by using the tags. :-)

**Comment by Skocimis** [comment]
Thank you for your feedback. I have removed the version field from the composer.json file as per your recommendation. Moving forward, we will use VCS tags to manage our package versions and allow Packagist to automatically fetch new versions from those tags. I am closing this issue as it has been resolved.

**Comment by Maikuolan** [comment]
Happy to help. :-)
