### ISSUE TITLE
Required PHP version in composer.json

### ISSUE THREAD

**Issue by Maikuolan** [Skocimis/textflow-php#3]
Would be good to explicitly state in the `composer.json` file the PHP version requirements for the package.

E.g.,
```JSON
    "require": {
        "php": "^7|^8"
    }
```

**Comment by Skocimis** [comment]
Thank you for your suggestion. I've added the PHP version requirement to the composer.json file. Now it explicitly states that the package requires PHP version 7.4 or higher, including any PHP 8 versions. I appreciate your input which helps to make our package better and easier to use.

**Comment by Maikuolan** [comment]
Happy to help. :-)
