### ISSUE TITLE
Undefined type 'TextFlow\SmsApi\Client'.

### ISSUE THREAD

**Issue by madfortech** [Skocimis/textflow-php#4]
![Capture](https://github.com/Skocimis/textflow-php/assets/21261716/1ec89f3e-d4c7-4756-9f92-2571e05fe845)
![Capture-](https://github.com/Skocimis/textflow-php/assets/21261716/1e6939ba-1590-42c9-a5e5-e5354df4c020)

php version PHP 8.1.12
laravel 10.9.0

please help me folks :)

**Comment by Skocimis** [comment]
We have forgotten to include a namespace in the file. It is fixed now in version v1.6.4, so try updating our package. 
Also, when initializing our TextFlowClient class, you should only provide an API key, not the API secret.

**Comment by madfortech** [comment]
i used this namespace 
use TextFlow\SMSApi\TextFlowClient;
its working in local development

**Comment by Skocimis** [comment]
So it is working now and I can close the issue?

**Comment by madfortech** [comment]
yes you can close.
